sudo: false
language: c++
compiler:
 - clang
 - gcc

install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: ./travis-build.sh

os:
 - linux
 - osx

matrix:
  exclude:
    - os: osx
      compiler: gcc

addons:
 apt:
  sources:
   - llvm-toolchain-precise-3.8
   - ubuntu-toolchain-r-test
   - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
  packages:
   - libllvm3.8
   - libllvm3.8-dbg
   - llvm-3.8
   - llvm-3.8-dev
   - llvm-3.8-runtime
   - gcc-4.8
   - g++-4.8
   - libedit-dev
   - clang
   - cmake
   - cmake-data

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install homebrew/versions/llvm38;
    fi