sudo: false
language: c++
compiler:
 - clang
 - gcc

install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
 - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" != "osx" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

script: ./travis-build.sh

os:
 - linux
 - osx

matrix:
  exclude:
    - os: osx
      compiler: gcc

addons:
 apt:
  sources:
   - llvm-toolchain-precise-3.8
   - ubuntu-toolchain-r-test
   - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
  packages:
   - libllvm3.8
   - libllvm3.8-dbg
   - llvm-3.8
   - llvm-3.8-dev
   - llvm-3.8-runtime
   - gcc-5
   - g++-5
   - libedit-dev
   - clang-3.8
   - cmake
   - cmake-data

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install homebrew/versions/llvm38;
    fi