sudo: false

language: c++
compiler:
 - clang
 - gcc

install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
 - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" != "osx" ]; then export CXX="clang++-5.0" CC="clang-5.0"; fi

script: ./travis-build.sh

os:
 - linux
   dist: trusty
# - osx

matrix:
  exclude:
    - os: osx
      compiler: gcc

addons:
 apt:
  sources:
   - llvm-toolchain-trusty-5.0
   - ubuntu-toolchain-r-test
  packages:
   - gcc-6
   - g++-6
   - libedit-dev
   - clang-5.0